name: golangci-lint
on:
    push:
        branches:
    pull_request:
jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
                submodules: 'true'
            - name: Set up LibGL, Mesa & X11 libraries
              run: |
                sudo apt-get --allow-releaseinfo-change update
                sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev
                sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libsdl2-dev libasound2-dev
            - name: Set up Go environment
              uses: actions/setup-go@v2.1.3
              with:
                go-version: 1.16.4
              id: go
            - run: go version
            - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
            - run: golangci-lint run ./...
